const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const Module = require('node:module');

const root = path.join(__dirname, '..');

function createMiniExpress() {
  function Router() {
    const routes = [];
    const router = async (req, res, next) => {
      for (const route of routes) {
        if (route.method === req.method && route.path === req.url.split('?')[0]) {
          return route.handler(req, res, next);
        }
      }
      return next();
    };
    router.get = (routePath, handler) => routes.push({ method: 'GET', path: routePath, handler });
    return router;
  }
  return { Router };
}

function loadPlannerUiRouter() {
  const routePath = require.resolve('../src/routes/planner.ui.routes');
  delete require.cache[routePath];
  const originalLoad = Module._load;
  Module._load = function patchedLoad(request, parent, isMain) {
    if (request === 'express') return createMiniExpress();
    return originalLoad.call(this, request, parent, isMain);
  };
  try {
    return require('../src/routes/planner.ui.routes');
  } finally {
    Module._load = originalLoad;
  }
}

async function renderPlannerPage() {
  const { createPlannerUiRouter } = loadPlannerUiRouter();
  const router = createPlannerUiRouter();
  let html = '';
  await router(
    { method: 'GET', url: '/planner' },
    {
      setHeader() {},
      end(value) { html = value; }
    },
    () => {
      throw new Error('PLANNER_ROUTE_NOT_FOUND');
    }
  );
  return html;
}

function scriptFrom(html) {
  const match = html.match(/<script>([\s\S]+)<\/script>/);
  assert.ok(match, 'planner page script must exist');
  return match[1];
}

function createElement(id) {
  const classes = new Set(['approveRoadmap', 'startAutopilot', 'proposalView', 'startView'].includes(id) ? ['hidden'] : []);
  const element = {
    id,
    value: '',
    disabled: false,
    textContent: '',
    innerHTML: '',
    className: '',
    listeners: {},
    addEventListener(name, handler) {
      this.listeners[name] = handler;
    },
    reset() {
      this.value = '';
    },
    classList: {
      add(name) { classes.add(name); },
      remove(name) { classes.delete(name); },
      toggle(name, force) {
        const shouldAdd = force === undefined ? !classes.has(name) : Boolean(force);
        if (shouldAdd) classes.add(name);
        else classes.delete(name);
      },
      contains(name) { return classes.has(name); }
    }
  };
  return element;
}

function createHarness(html, fetchImpl = async () => ({ ok: true, json: async () => ({}) })) {
  const elements = new Map();
  const document = {
    getElementById(id) {
      if (!elements.has(id)) elements.set(id, createElement(id));
      return elements.get(id);
    }
  };
  const context = {
    document,
    fetch: fetchImpl,
    encodeURIComponent,
    String,
    Boolean,
    Number,
    Array,
    Error
  };
  vm.createContext(context);
  vm.runInContext(`${scriptFrom(html)}\nglobalThis.__planner = { state, els, renderProposal, loadProposal };`, context);
  return { context, elements, planner: context.__planner };
}

function proposal(overrides = {}) {
  return {
    roadmap_id: 'roadmap_1',
    title: 'Persisted W01 Roadmap',
    state: 'PROPOSED',
    approval_status: 'PENDING',
    objective: 'Review a persisted roadmap before approval.',
    summary: 'The roadmap is generated by Brain and remains read-only in Planner.',
    risks: ['Approval could be confused with execution'],
    dependencies: ['Stored Planner proposal endpoint'],
    assumptions: ['A human reviewer decides whether to approve'],
    original_request: 'Build the Planner roadmap review screen',
    provenance: { source: 'PLANNER_BRAIN_RUN', original_request: 'Build the Planner roadmap review screen' },
    workspace_id: 'workspace_scb',
    project_id: 'project_scb_development',
    milestones: [
      {
        id: 'm2',
        order: 2,
        title: 'Executor Follow-up',
        objective: 'Prepare future executor work after approval.',
        description: 'Describe the executor-facing milestone without starting it.',
        executor_required: true,
        dependencies: ['m1'],
        risks: ['Could be started too early'],
        success_criteria: ['Start remains separate from approval'],
        state: 'PROPOSED'
      },
      {
        id: 'm1',
        order: 1,
        title: 'Brain Review',
        objective: 'Explain the planning decision.',
        description: 'Summarize the roadmap and approval boundary.',
        executor_required: false,
        dependencies: [],
        risks: [],
        success_criteria: ['Reviewer sees complete proposal fields'],
        state: 'PROPOSED'
      }
    ],
    ...overrides
  };
}

test('/planner contains a clearly labeled Roadmap Proposal review section', async () => {
  const html = await renderPlannerPage();
  assert.match(html, /id="proposalView"/);
  assert.match(html, /ROADMAP PROPOSAL/);
  assert.match(html, /Roadmap Proposal|ROADMAP PROPOSAL/);
});

test('proposal rendering uses persisted retrieval data and shows complete review fields', async () => {
  const html = await renderPlannerPage();
  const { planner } = createHarness(html);
  planner.renderProposal(proposal());
  const rendered = planner.els.proposalView.innerHTML;

  assert.match(rendered, /Persisted W01 Roadmap/);
  assert.match(rendered, /Review a persisted roadmap before approval/);
  assert.match(rendered, /The roadmap is generated by Brain/);
  assert.match(rendered, /PROPOSED - awaiting human approval/);
  assert.match(rendered, /Awaiting explicit approval/);
  assert.match(rendered, /Approval could be confused with execution/);
  assert.match(rendered, /Stored Planner proposal endpoint/);
  assert.match(rendered, /A human reviewer decides whether to approve/);
  assert.match(rendered, /Original Planner request/);
  assert.match(rendered, /Build the Planner roadmap review screen/);
  assert.match(rendered, /Proposal source/);
  assert.match(rendered, /PLANNER_BRAIN_RUN/);
  assert.doesNotMatch(rendered, /tenant_facundo_group|MRAPI_CONTROL|EXECUTION_RUN|codex_handoff/);
});

test('milestones render in persisted order with read-only details and readable empty states', async () => {
  const html = await renderPlannerPage();
  const { planner } = createHarness(html);
  planner.renderProposal(proposal());
  const rendered = planner.els.proposalView.innerHTML;

  assert.ok(rendered.indexOf('Brain Review') < rendered.indexOf('Executor Follow-up'));
  assert.match(rendered, /Milestone ID: m1/);
  assert.match(rendered, /Milestone ID: m2/);
  assert.match(rendered, /Objective \/ expected outcome/);
  assert.match(rendered, /Explain the planning decision/);
  assert.match(rendered, /Description/);
  assert.match(rendered, /Summarize the roadmap and approval boundary/);
  assert.match(rendered, /Executor requirement/);
  assert.match(rendered, /Brain only/);
  assert.match(rendered, /Executor required/);
  assert.match(rendered, /No dependencies/);
  assert.match(rendered, /None recorded/);
  assert.match(rendered, /Success criteria/);
  assert.match(rendered, /Persisted lifecycle state/);
});

test('PROPOSED state explains approval boundary, enables approval, and hides Start Autopilot', async () => {
  const html = await renderPlannerPage();
  const { planner } = createHarness(html);
  planner.renderProposal(proposal());

  assert.match(planner.els.proposalView.innerHTML, /No Autopilot execution has started/);
  assert.match(planner.els.proposalView.innerHTML, /Awaiting explicit human approval/);
  assert.equal(planner.els.approve.classList.contains('hidden'), false);
  assert.equal(planner.els.start.classList.contains('hidden'), true);
});

test('approval payload is affirmative-only, refresh is side-effect free, and approval does not start', async () => {
  const html = await renderPlannerPage();
  const calls = [];
  const responses = [
    proposal(),
    { ok: true },
    proposal({ state: 'ACTIVE', approval_status: 'APPROVED', milestones: proposal().milestones.map((m) => ({ ...m, state: 'PENDING' })) })
  ];
  const { planner } = createHarness(html, async (url, options = {}) => {
    calls.push({ url, options });
    const body = responses.shift();
    return { ok: true, json: async () => body };
  });

  planner.els.proposalId.value = 'roadmap_1';
  await planner.els.refresh.listeners.click();
  assert.equal(calls.length, 1);
  assert.match(calls[0].url, /\/api\/planner\/proposals\/roadmap_1$/);
  assert.doesNotMatch(calls[0].url, /\/approve|\/start/);

  await planner.els.approve.listeners.click();
  assert.equal(calls.length, 3);
  assert.match(calls[1].url, /\/approve$/);
  assert.equal(calls[1].options.body, JSON.stringify({ approve: true }));
  assert.doesNotMatch(calls.map((call) => call.url).join('\n'), /\/start/);
  assert.match(planner.els.proposalView.innerHTML, /ACTIVE \/ APPROVED/);
  assert.equal(planner.els.start.classList.contains('hidden'), false);
});

test('terminal and malformed proposals are not shown as ordinary startable work', async () => {
  const html = await renderPlannerPage();
  const { planner } = createHarness(html);

  planner.renderProposal(proposal({ state: 'BLOCKED', approval_status: 'PENDING' }));
  assert.match(planner.els.proposalView.innerHTML, /BLOCKED/);
  assert.match(planner.els.proposalView.innerHTML, /not presented as ordinary executable approved work/);
  assert.equal(planner.els.approve.classList.contains('hidden'), true);
  assert.equal(planner.els.start.classList.contains('hidden'), true);

  planner.renderProposal(proposal({ state: 'CANCELLED', approval_status: 'APPROVED' }));
  assert.match(planner.els.proposalView.innerHTML, /CANCELLED/);
  assert.equal(planner.els.start.classList.contains('hidden'), true);

  planner.renderProposal({ roadmap_id: 'bad', title: 'Incomplete', state: 'PROPOSED', approval_status: 'PENDING' });
  assert.match(planner.els.proposalView.innerHTML, /incomplete or malformed/i);
  assert.equal(planner.els.approve.classList.contains('hidden'), true);
});

test('proposal review remains read-only and exposes no unauthorized controls', async () => {
  const source = fs.readFileSync(path.join(root, 'src', 'routes', 'planner.ui.routes.js'), 'utf8');
  const html = await renderPlannerPage();

  assert.doesNotMatch(html, /contenteditable|draggable|editMilestone|editTitle|deleteMilestone|regenerate|reorder|drag\/drop/i);
  assert.doesNotMatch(html, /name="tenant_id"|id="tenantId"/);
  assert.doesNotMatch(source, /fetch\('\/api\/tasks|fetch\('\/api\/runs|\/regenerate|\/delete|\/reorder|\/executor/);
});
